#pragma once

#define TRADEHELPERxstr( s ) TRADEHELPERStringify( s )
#define TRADEHELPERStringify( s ) #s

#define TRADEHELPER_BINARY_NAME   "TradeHelperForPoe"
#define TRADEHELPER_COMPANY_NAME  "Mwoua"

#define TRADEHELPER_MAJOR_VERSION 0
#define TRADEHELPER_MINOR_VERSION 0
#define TRADEHELPER_PATCH_VERSION 0
#define TRADEHELPER_BUILD_NUMBER  0

#define TRADEHELPER_VERSION_MACRO( a, b, c, d, e ) TRADEHELPERxstr( a.b.c.d e )
#define TRADEHELPER_VERSION_STRING TRADEHELPER_VERSION_MACRO( TRADEHELPER_MAJOR_VERSION, TRADEHELPER_MINOR_VERSION, TRADEHELPER_PATCH_VERSION, TRADEHELPER_BUILD_NUMBER )
