name: Build_Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.1'

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.12.1
    
    - name: Configure
      run: cmake -D CMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -G "Ninja" -B ${{ github.workspace }}/build -S ${{ github.workspace }}
    
    - name: Build
      run: cmake --build ${{ github.workspace }}/build

    - name: Install
      run: |
        cmake --install ${{ github.workspace }}/build --prefix ${{ github.workspace }}/install
        mv ${{ github.workspace }}/install/bin/qt.conf ${{ github.workspace }}/install/
        rmdir ${{ github.workspace }}/install/bin

    - name: artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_linux
        path: ${{ github.workspace }}/install
        if-no-files-found: error
